
name: Génération du JSON depuis Excel OneDrive

on:
  schedule:
    - cron: '0 8 * * *'  # Tous les jours à 8h
  workflow_dispatch:     # Permet de lancer manuellement
  push:
    paths:
      - '.github/workflows/update-json.yml'

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du dépôt
      uses: actions/checkout@v3

    - name: Installer Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Installer les dépendances
      run: |
        pip install pandas openpyxl requests
    - name: Télécharger le fichier Excel depuis OneDrive
      run: |
        curl -L "https://toulouse3.sharepoint.com/:x:/r/sites/IUTA-CRI/_layouts/15/Doc2.aspx?action=edit&sourcedoc=%7B6eb8d196-8d0b-4e81-8964-b7860d8851db%7D&wdOrigin=TEAMS-MAGLEV.undefined_ns.rwc&wdExp=TEAMS-TREATMENT&wdhostclicktime=1756803475524&web=1" -o Portail_TICE.xlsx
    - name: Générer le fichier JSON
      run: python update_json.py

    - name: Commit et push du JSON mis à jour
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add updated_services.json
        git commit -m "Mise à jour automatique du JSON depuis Excel OneDrive"
        git push
